server:
  port: 8202
spring:
  application:
    name: service-item
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848

feign:
  client:
    default-config:
      read-timeout: 600000
      connect-timeout: 600000
